#!/bin/bash
# in order to run matplotlib, this needs to be used instead of 'python'

# what real Python executable to use
PYVER=3.5
PATHTOPYTHON=/usr/local/bin/
# PATHTOPYTHON=`which python3`
# PYTHON=${PATHTOPYTHON}python${PYVER}
PYTHON=/Library/Frameworks/Python.framework/Versions/3.5/bin/python3

# find the root of the virtualenv
ENV=`$PYTHON -c "import os; print(os.path.abspath(os.path.join(os.path.dirname(\"$0\"), 'env')))"`
# ENV=`$PYTHON -c "import os; print(os.path.abspath(os.path.dirname(\"$0\")))"`

# now run Python with the virtualenv set as Python's HOME
export PYTHONHOME=$ENV

exec $PYTHON "$@"
